import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:intl/intl.dart'; // For date formatting

// --- Data Models ---
// Assuming a simple Customer model for now.
// In a real app, this would likely be more detailed and fetched from a data source.
class Customer {
  final String id;
  final String name;
  final String customerCode;

  Customer({required this.id, required this.name, required this.customerCode});
}

class Receipt {
  String? id; // Unique ID for the receipt (e.g., generated by backend)
  String receiptNo;
  String customerId;
  String customerName; // Store for display convenience
  String customerCode; // Store for display/filtering
  DateTime receiptDate;
  String paymentType;
  double debtAmount; // Outstanding debt amount before this payment
  double transactionAmount; // The actual amount being paid/transacted
  double
  paidAmount; // Confirmed paid amount (might be same as transactionAmount)
  String? chequeNo;
  String? chequeType;
  String? bankName;
  String? paymentReferenceNo; // e.g., online transaction ID, slip number

  Receipt({
    this.id,
    required this.receiptNo,
    required this.customerId,
    required this.customerName,
    required this.customerCode,
    required this.receiptDate,
    required this.paymentType,
    required this.debtAmount,
    required this.transactionAmount,
    required this.paidAmount,
    this.chequeNo,
    this.chequeType,
    this.bankName,
    this.paymentReferenceNo,
  });
}

// --- Mock Data for Customer Selection ---
final List<Customer> _mockCustomers = [
  Customer(
    id: 'cust_001',
    name: 'AHS3185 S02 KANESAN',
    customerCode: '3000/S02',
  ),
  Customer(
    id: 'cust_002',
    name: 'Beta Wholesale Sdn Bhd',
    customerCode: 'CUST1001',
  ),
  Customer(
    id: 'cust_003',
    name: 'Gamma Retail Enterprise',
    customerCode: 'CUST2050',
  ),
  Customer(id: 'cust_004', name: 'KUMAR ENTERPRISE', customerCode: '3000/S03'),
];

// --- Receipt Form Page ---
class ReceiptFormPage extends StatefulWidget {
  final Receipt?
  receiptToEdit; // Pass a receipt to pre-fill the form for editing

  const ReceiptFormPage({super.key, this.receiptToEdit});

  @override
  State<ReceiptFormPage> createState() => _ReceiptFormPageState();
}

class _ReceiptFormPageState extends State<ReceiptFormPage> {
  final _formKey = GlobalKey<FormState>();

  // --- Controllers ---
  late TextEditingController _receiptNoController;
  Customer? _selectedCustomer; // For customer selection
  late TextEditingController _debtAmountController;
  late TextEditingController _transactionAmountController; // Tr Amount
  late TextEditingController _paidAmountController;
  late TextEditingController _chequeNoController;
  late TextEditingController _bankNameController;
  late TextEditingController _paymentReferenceNoController; // Payment No

  // --- Dropdown State Variables ---
  String? _selectedPaymentType;
  final List<String> _paymentTypeOptions = [
    'Cash',
    'Cheque',
    'Online Transfer',
    'Card',
    'Other',
  ];
  String? _selectedChequeType;
  final List<String> _chequeTypeOptions = ['Local', 'Outstation', 'Post-Dated'];

  DateTime _selectedReceiptDate = DateTime.now();

  @override
  void initState() {
    super.initState();
    final receipt = widget.receiptToEdit;

    _receiptNoController = TextEditingController(
      text: receipt?.receiptNo ?? _generateNewReceiptNo(),
    );
    _debtAmountController = TextEditingController(
      text: receipt?.debtAmount.toStringAsFixed(2) ?? '0.00',
    );
    _transactionAmountController = TextEditingController(
      text: receipt?.transactionAmount.toStringAsFixed(2) ?? '0.00',
    );
    _paidAmountController = TextEditingController(
      text: receipt?.paidAmount.toStringAsFixed(2) ?? '0.00',
    );
    _chequeNoController = TextEditingController(text: receipt?.chequeNo ?? '');
    _bankNameController = TextEditingController(text: receipt?.bankName ?? '');
    _paymentReferenceNoController = TextEditingController(
      text: receipt?.paymentReferenceNo ?? '',
    );

    if (receipt != null) {
      _selectedReceiptDate = receipt.receiptDate;
      // Attempt to find the customer in the mock list
      try {
        _selectedCustomer = _mockCustomers.firstWhere(
          (c) => c.id == receipt.customerId,
        );
      } catch (e) {
        _selectedCustomer = null; // Customer not found in mock list
      }
      if (_paymentTypeOptions.contains(receipt.paymentType)) {
        _selectedPaymentType = receipt.paymentType;
      }
      if (receipt.chequeType != null &&
          _chequeTypeOptions.contains(receipt.chequeType)) {
        _selectedChequeType = receipt.chequeType;
      }
    }

    // Listener to auto-fill paid amount from transaction amount if empty
    _transactionAmountController.addListener(() {
      if (_paidAmountController.text.isEmpty ||
          _paidAmountController.text == '0.00') {
        _paidAmountController.text = _transactionAmountController.text;
      }
    });
  }

  @override
  void dispose() {
    _receiptNoController.dispose();
    _debtAmountController.dispose();
    _transactionAmountController.dispose();
    _paidAmountController.dispose();
    _chequeNoController.dispose();
    _bankNameController.dispose();
    _paymentReferenceNoController.dispose();
    super.dispose();
  }

  String _generateNewReceiptNo() {
    // Basic receipt number generation, replace with your actual logic
    final timestamp = DateTime.now().millisecondsSinceEpoch
        .toString()
        .substring(7);
    return 'RCPT-$timestamp';
  }

  Future<void> _selectReceiptDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedReceiptDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2101),
    );
    if (picked != null && picked != _selectedReceiptDate) {
      setState(() {
        _selectedReceiptDate = picked;
      });
    }
  }

  void _saveReceipt() {
    if (_formKey.currentState!.validate()) {
      if (_selectedCustomer == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Please select a customer.'),
            backgroundColor: Colors.orange,
          ),
        );
        return;
      }
      if (_selectedPaymentType == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Please select a payment type.'),
            backgroundColor: Colors.orange,
          ),
        );
        return;
      }

      final newReceipt = Receipt(
        id: widget.receiptToEdit?.id, // Keep existing ID if editing
        receiptNo: _receiptNoController.text,
        customerId: _selectedCustomer!.id,
        customerName: _selectedCustomer!.name,
        customerCode: _selectedCustomer!.customerCode,
        receiptDate: _selectedReceiptDate,
        paymentType: _selectedPaymentType!,
        debtAmount: double.tryParse(_debtAmountController.text) ?? 0.0,
        transactionAmount:
            double.tryParse(_transactionAmountController.text) ?? 0.0,
        paidAmount: double.tryParse(_paidAmountController.text) ?? 0.0,
        chequeNo:
            _chequeNoController.text.isNotEmpty
                ? _chequeNoController.text
                : null,
        chequeType:
            _selectedPaymentType == 'Cheque' ? _selectedChequeType : null,
        bankName:
            _bankNameController.text.isNotEmpty
                ? _bankNameController.text
                : null,
        paymentReferenceNo:
            _paymentReferenceNoController.text.isNotEmpty
                ? _paymentReferenceNoController.text
                : null,
      );

      // --- TODO: Implement actual save logic (e.g., API call, database update) ---
      print('Saving Receipt:');
      print('Receipt No: ${newReceipt.receiptNo}');
      print(
        'Customer: ${newReceipt.customerName} (${newReceipt.customerCode})',
      );
      print('Date: ${DateFormat('yyyy-MM-dd').format(newReceipt.receiptDate)}');
      print('Payment Type: ${newReceipt.paymentType}');
      print('Paid Amount: ${newReceipt.paidAmount}');
      // ... print other fields

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            widget.receiptToEdit == null
                ? 'Receipt Created!'
                : 'Receipt Updated!',
          ),
          backgroundColor: Colors.green,
        ),
      );

      if (Navigator.canPop(context)) {
        Navigator.pop(context, newReceipt); // Pass the new/updated receipt back
      }
    }
  }

  void _handlePreview() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Preview action tapped (not implemented).'),
        backgroundColor: Colors.blueGrey,
      ),
    );
    // TODO: Implement preview logic
  }

  void _handlePrint() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Print action tapped (not implemented).'),
        backgroundColor: Colors.blueGrey,
      ),
    );
    // TODO: Implement print logic
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.receiptToEdit == null
              ? 'Create Customer Receipt'
              : 'Edit Customer Receipt',
        ),
        actions: [
          if (widget.receiptToEdit !=
              null) // Show print only when editing existing
            IconButton(
              icon: const Icon(Icons.print_outlined),
              onPressed: _handlePrint,
              tooltip: 'Print',
            ),
          IconButton(
            icon: const Icon(Icons.save_alt_outlined),
            onPressed: _saveReceipt,
            tooltip: 'Save Receipt',
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              // Receipt No
              TextFormField(
                controller: _receiptNoController,
                decoration: const InputDecoration(
                  labelText: 'Receipt No',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(FontAwesomeIcons.hashtag),
                ),
                readOnly:
                    widget.receiptToEdit !=
                    null, // Often non-editable after creation
                validator:
                    (value) =>
                        (value == null || value.isEmpty)
                            ? 'Receipt No cannot be empty'
                            : null,
              ),
              const SizedBox(height: 16),

              // Receipt Date
              InkWell(
                onTap: () => _selectReceiptDate(context),
                child: InputDecorator(
                  decoration: const InputDecoration(
                    labelText: 'Receipt Date',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(FontAwesomeIcons.calendarDay),
                  ),
                  child: Text(
                    DateFormat('dd MMM yyyy').format(_selectedReceiptDate),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Customer Autocomplete/Dropdown
              Autocomplete<Customer>(
                displayStringForOption:
                    (Customer option) =>
                        '${option.customerCode} - ${option.name}',
                optionsBuilder: (TextEditingValue textEditingValue) {
                  if (textEditingValue.text.isEmpty) {
                    return const Iterable<Customer>.empty();
                  }
                  return _mockCustomers
                      .where((Customer option) {
                        return option.name.toLowerCase().contains(
                              textEditingValue.text.toLowerCase(),
                            ) ||
                            option.customerCode.toLowerCase().contains(
                              textEditingValue.text.toLowerCase(),
                            );
                      })
                      .take(5); // Show top 5 suggestions
                },
                onSelected: (Customer selection) {
                  setState(() {
                    _selectedCustomer = selection;
                    // TODO: Optionally fetch customer's outstanding debt amount here
                    // _debtAmountController.text = fetchedDebtAmount.toStringAsFixed(2);
                  });
                  FocusScope.of(context).unfocus(); // Hide keyboard
                },
                fieldViewBuilder: (
                  BuildContext context,
                  TextEditingController fieldTextEditingController,
                  FocusNode fieldFocusNode,
                  VoidCallback onFieldSubmitted,
                ) {
                  // Pre-fill if a customer is already selected (e.g., when editing)
                  if (_selectedCustomer != null &&
                      fieldTextEditingController.text.isEmpty) {
                    fieldTextEditingController.text =
                        '${_selectedCustomer!.customerCode} - ${_selectedCustomer!.name}';
                  }
                  return TextFormField(
                    controller: fieldTextEditingController,
                    focusNode: fieldFocusNode,
                    decoration: InputDecoration(
                      labelText: 'Customer',
                      hintText: 'Type Customer Code or Name',
                      border: const OutlineInputBorder(),
                      prefixIcon: const Icon(Icons.person_search_outlined),
                      suffixIcon:
                          fieldTextEditingController.text.isNotEmpty
                              ? IconButton(
                                icon: const Icon(Icons.clear),
                                onPressed: () {
                                  fieldTextEditingController.clear();
                                  setState(() {
                                    _selectedCustomer = null;
                                    _debtAmountController.text =
                                        '0.00'; // Reset debt amount
                                  });
                                },
                              )
                              : null,
                    ),
                    validator:
                        (value) =>
                            _selectedCustomer == null && value!.isNotEmpty
                                ? 'Please select a valid customer from suggestions'
                                : null,
                  );
                },
                optionsViewBuilder: (
                  BuildContext context,
                  AutocompleteOnSelected<Customer> onSelected,
                  Iterable<Customer> options,
                ) {
                  return Align(
                    alignment: Alignment.topLeft,
                    child: Material(
                      elevation: 4.0,
                      child: ConstrainedBox(
                        constraints: const BoxConstraints(maxHeight: 200),
                        child: ListView.builder(
                          padding: EdgeInsets.zero,
                          itemCount: options.length,
                          itemBuilder: (BuildContext context, int index) {
                            final Customer option = options.elementAt(index);
                            return InkWell(
                              onTap: () => onSelected(option),
                              child: ListTile(
                                title: Text(option.customerCode),
                                subtitle: Text(option.name),
                              ),
                            );
                          },
                        ),
                      ),
                    ),
                  );
                },
              ),
              const SizedBox(height: 16),

              // Payment Type Dropdown
              DropdownButtonFormField<String>(
                value: _selectedPaymentType,
                decoration: const InputDecoration(
                  labelText: 'Payment Type',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(FontAwesomeIcons.creditCard),
                ),
                items:
                    _paymentTypeOptions.map((String type) {
                      return DropdownMenuItem<String>(
                        value: type,
                        child: Text(type),
                      );
                    }).toList(),
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedPaymentType = newValue;
                    // Clear cheque fields if payment type is not Cheque
                    if (newValue != 'Cheque') {
                      _chequeNoController.clear();
                      _selectedChequeType = null;
                      _bankNameController.clear();
                    }
                  });
                },
                validator:
                    (value) =>
                        value == null ? 'Please select a payment type' : null,
              ),
              const SizedBox(height: 16),

              // Debt Amount (OSTD Amount)
              TextFormField(
                controller: _debtAmountController,
                decoration: const InputDecoration(
                  labelText: 'Debt Amount (Outstanding)',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(FontAwesomeIcons.fileInvoiceDollar),
                ),
                keyboardType: const TextInputType.numberWithOptions(
                  decimal: true,
                ),
                // readOnly: true, // This might be fetched and non-editable
                validator: (value) {
                  if (value == null || value.isEmpty)
                    return 'Debt amount is required';
                  if (double.tryParse(value) == null) return 'Invalid number';
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Transaction Amount (Tr Amount)
              TextFormField(
                controller: _transactionAmountController,
                decoration: const InputDecoration(
                  labelText: 'Transaction Amount',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(FontAwesomeIcons.moneyBillTransfer),
                ),
                keyboardType: const TextInputType.numberWithOptions(
                  decimal: true,
                ),
                validator: (value) {
                  if (value == null || value.isEmpty)
                    return 'Transaction amount is required';
                  final amount = double.tryParse(value);
                  if (amount == null) return 'Invalid number';
                  if (amount <= 0) return 'Amount must be greater than 0';
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Paid Amount
              TextFormField(
                controller: _paidAmountController,
                decoration: const InputDecoration(
                  labelText: 'Paid Amount',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(FontAwesomeIcons.handHoldingDollar),
                ),
                keyboardType: const TextInputType.numberWithOptions(
                  decimal: true,
                ),
                validator: (value) {
                  if (value == null || value.isEmpty)
                    return 'Paid amount is required';
                  final amount = double.tryParse(value);
                  if (amount == null) return 'Invalid number';
                  if (amount <= 0) return 'Amount must be greater than 0';
                  // Optional: Validate against transaction amount or debt amount
                  // if (amount > (double.tryParse(_transactionAmountController.text) ?? 0)) {
                  //   return 'Paid amount cannot exceed transaction amount';
                  // }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Conditional Cheque Fields
              if (_selectedPaymentType == 'Cheque') ...[
                TextFormField(
                  controller: _chequeNoController,
                  decoration: const InputDecoration(
                    labelText: 'Cheque No',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(FontAwesomeIcons.moneyCheck),
                  ),
                  validator:
                      (value) =>
                          (_selectedPaymentType == 'Cheque' &&
                                  (value == null || value.isEmpty))
                              ? 'Cheque No is required for cheque payment'
                              : null,
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<String>(
                  value: _selectedChequeType,
                  decoration: const InputDecoration(
                    labelText: 'Cheque Type',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(
                      FontAwesomeIcons.moneyCheckDollar,
                    ), // Consider a different icon
                  ),
                  items:
                      _chequeTypeOptions.map((String type) {
                        return DropdownMenuItem<String>(
                          value: type,
                          child: Text(type),
                        );
                      }).toList(),
                  onChanged: (String? newValue) {
                    setState(() {
                      _selectedChequeType = newValue;
                    });
                  },
                  validator:
                      (value) =>
                          (_selectedPaymentType == 'Cheque' && value == null)
                              ? 'Cheque Type is required'
                              : null,
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _bankNameController,
                  decoration: const InputDecoration(
                    labelText: 'Bank Name',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(FontAwesomeIcons.buildingColumns),
                  ),
                  validator:
                      (value) =>
                          (_selectedPaymentType == 'Cheque' &&
                                  (value == null || value.isEmpty))
                              ? 'Bank Name is required for cheque payment'
                              : null,
                ),
                const SizedBox(height: 16),
              ],

              // Payment No (Reference No)
              TextFormField(
                controller: _paymentReferenceNoController,
                decoration: const InputDecoration(
                  labelText: 'Payment Ref No (e.g. Slip No)',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(FontAwesomeIcons.receipt),
                ),
              ),
              const SizedBox(height: 24),

              // Action Buttons
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  OutlinedButton.icon(
                    icon: const Icon(Icons.preview_outlined),
                    label: const Text('Preview'),
                    onPressed: _handlePreview,
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 12,
                      ),
                    ),
                  ),
                  OutlinedButton.icon(
                    icon: const Icon(Icons.print_outlined),
                    label: const Text('Print'),
                    onPressed: _handlePrint,
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 12,
                      ),
                    ),
                  ),
                  ElevatedButton.icon(
                    icon: const Icon(Icons.save),
                    label: const Text('Save'),
                    onPressed: _saveReceipt,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Theme.of(context).primaryColor,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 20,
                        vertical: 12,
                      ),
                    ),
                  ),
                  TextButton.icon(
                    icon: const Icon(
                      Icons.cancel_outlined,
                      color: Colors.redAccent,
                    ),
                    label: const Text(
                      'Cancel',
                      style: TextStyle(color: Colors.redAccent),
                    ),
                    onPressed: () {
                      if (Navigator.canPop(context)) Navigator.pop(context);
                    },
                    style: TextButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 12,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
