class Receipt {
  String? id; // Unique ID for the receipt (e.g., generated by backend)
  String receiptNo;
  String customerId;
  String customerName; // Store for display convenience
  String customerCode; // Store for display/filtering
  DateTime receiptDate;
  String paymentType;
  double debtAmount; // Outstanding debt amount before this payment
  double transactionAmount; // The actual amount being paid/transacted
  double
  paidAmount; // Confirmed paid amount (might be same as transactionAmount)
  String? chequeNo;
  String? chequeType;
  String? bankName;
  String? paymentReferenceNo; // e.g., online transaction ID, slip number

  Receipt({
    this.id,
    required this.receiptNo,
    required this.customerId,
    required this.customerName,
    required this.customerCode,
    required this.receiptDate,
    required this.paymentType,
    required this.debtAmount,
    required this.transactionAmount,
    required this.paidAmount,
    this.chequeNo,
    this.chequeType,
    this.bankName,
    this.paymentReferenceNo,
  });
}
